name: Release Packages

on:
  push:
    branches:
      - master
    paths:
      - .changeset/**
      - packages/**
      - apps/**
      - pnpm-workspace.yaml
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/release-packages.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-packages:
    name: Release Packages
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      id-token: write # Required for OIDC
      packages: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm run test
      # - name: Create Version PR or Publish Packages
      #   uses: changesets/action@v1
      #   with:
      #     version: pnpm run version:packages
      #     publish: pnpm run release:packages
      #     title: "chore: version packages"
      #     commit: "chore: version packages"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
